#!/bin/zsh -e

if [ $(id -u) -eq 0 ]; then
    echo "I'll ask you when I think I need root permissions, Ok?" >&2
    exit 1
fi

case $(uname) in
    Linux)
        rtgrp=root
        ;;
    OpenBSD)
        rtgrp=wheel
        ;;
esac

echo "Setting the right permissions for the portsdir."
sudo chown -R ${USER}:$rtgrp /usr/cruxports

echo installing pkgutils
sudo install -d /usr/local/libexec
sudo install -m 755 -d                    /usr/local/bin
sudo install -m 755 pkgadd                /usr/local/bin
sudo install -m 755 pkgrm                 /usr/local/bin
sudo install -m 755 pkginfo               /usr/local/bin
sudo install -m 755 pkgmk                 /usr/local/bin
sudo install -m 755 pkgmk.buildwrapper    /usr/local/libexec


echo "Creating work directories."
sudo install -d -g $rtgrp -o $USER /usr/pkgmk/source /usr/pkgmk/package /usr/pkgmk/work

echo "Creating database directory."
sudo install -d /var/package/rejects

[ -e /etc/pkgadd.conf ] || sudo install -m 644 pkgadd.conf           /etc/pkgadd.conf
[ -e /etc/pkgmk.conf ]  || sudo install -m 644 pkgmk.conf            /etc/pkgmk.conf

echo 'building the first port! pkgutils!'
pkgmk -f
echo 'Adding it...'
sudo pkgadd -f /usr/pkgmk/package/pkgutils_*.pkg.tar.gz
echo "Setting the right permissions on the builddir."
sudo chown    ${USER}:$rtgrp /usr/pkgmk/*

echo "Congratulations, you have got cruxports installed."
echo "And you won't even have to reboot. ;-)"
